"""Unit tests for the AccessLogEntry and AccessLog models.

This module tests the access logging models including:
- AccessLogEntry instantiation, validation, and properties
- AccessLog operations (log, query, get_by_id, clear, statistics)
- Query filtering by various criteria
- Pagination (limit and offset)
- Capacity management (max_entries)

Test Organization:
- TestAccessLogEntry: Model instantiation and properties
- TestAccessLog: Basic operations (log, clear, get_by_id)
- TestAccessLogQuery: Query filtering and pagination
- TestAccessLogStatistics: Statistics and capacity
"""

from datetime import datetime, timedelta, timezone

import pytest

from ues.models.access_log import (
    AccessLog,
    AccessLogEntry,
    generate_log_id,
)


# =============================================================================
# Helper Functions Tests
# =============================================================================


class TestHelperFunctions:
    """Tests for module-level helper functions."""
    
    def test_generate_log_id_is_uuid(self):
        """Test that generate_log_id returns a valid UUID string."""
        log_id = generate_log_id()
        
        # UUID format: 8-4-4-4-12 hex characters with dashes
        assert len(log_id) == 36
        parts = log_id.split("-")
        assert len(parts) == 5
        assert [len(p) for p in parts] == [8, 4, 4, 4, 12]
    
    def test_generate_log_id_unique(self):
        """Test that generate_log_id returns unique values."""
        ids = [generate_log_id() for _ in range(100)]
        
        assert len(ids) == len(set(ids))


# =============================================================================
# AccessLogEntry Tests
# =============================================================================


class TestAccessLogEntry:
    """Tests for AccessLogEntry model instantiation and properties."""
    
    def test_instantiation_with_required_fields(self):
        """Test that AccessLogEntry can be instantiated with required fields."""
        entry = AccessLogEntry(
            method="GET",
            path="/email/state",
            status_code=200,
            duration_ms=15.5,
        )
        
        assert entry.method == "GET"
        assert entry.path == "/email/state"
        assert entry.status_code == 200
        assert entry.duration_ms == 15.5
        # Check defaults
        assert entry.key_id is None
        assert entry.key_name is None
        assert entry.client_ip is None
        assert entry.user_agent is None
        assert entry.error_detail is None
    
    def test_instantiation_with_all_fields(self):
        """Test that AccessLogEntry can be instantiated with all fields."""
        timestamp = datetime(2024, 1, 1, 12, 0, 0, tzinfo=timezone.utc)
        
        entry = AccessLogEntry(
            log_id="custom-id-123",
            timestamp=timestamp,
            method="POST",
            path="/email/send",
            key_id="ues_abc123",
            key_name="Email Bot",
            status_code=201,
            duration_ms=45.2,
            client_ip="192.168.1.100",
            user_agent="Mozilla/5.0",
            error_detail=None,
        )
        
        assert entry.log_id == "custom-id-123"
        assert entry.timestamp == timestamp
        assert entry.method == "POST"
        assert entry.path == "/email/send"
        assert entry.key_id == "ues_abc123"
        assert entry.key_name == "Email Bot"
        assert entry.status_code == 201
        assert entry.duration_ms == 45.2
        assert entry.client_ip == "192.168.1.100"
        assert entry.user_agent == "Mozilla/5.0"
        assert entry.error_detail is None
    
    def test_default_log_id_generated(self):
        """Test that a unique log_id is generated by default."""
        entry1 = AccessLogEntry(method="GET", path="/", status_code=200, duration_ms=1.0)
        entry2 = AccessLogEntry(method="GET", path="/", status_code=200, duration_ms=1.0)
        
        assert entry1.log_id != entry2.log_id
        assert len(entry1.log_id) == 36  # UUID format
    
    def test_default_timestamp_generated(self):
        """Test that a timestamp is generated by default."""
        before = datetime.now(timezone.utc)
        entry = AccessLogEntry(method="GET", path="/", status_code=200, duration_ms=1.0)
        after = datetime.now(timezone.utc)
        
        assert before <= entry.timestamp <= after
    
    def test_is_success_property_2xx(self):
        """Test is_success returns True for 2xx status codes."""
        for status in [200, 201, 204, 299]:
            entry = AccessLogEntry(
                method="GET", path="/", status_code=status, duration_ms=1.0
            )
            assert entry.is_success is True
            assert entry.is_error is False
    
    def test_is_success_property_non_2xx(self):
        """Test is_success returns False for non-2xx status codes."""
        for status in [100, 301, 400, 401, 403, 404, 500]:
            entry = AccessLogEntry(
                method="GET", path="/", status_code=status, duration_ms=1.0
            )
            assert entry.is_success is False
    
    def test_is_error_property_4xx(self):
        """Test is_error returns True for 4xx status codes."""
        for status in [400, 401, 403, 404, 422, 429, 499]:
            entry = AccessLogEntry(
                method="GET", path="/", status_code=status, duration_ms=1.0
            )
            assert entry.is_error is True
            assert entry.is_success is False
    
    def test_is_error_property_5xx(self):
        """Test is_error returns True for 5xx status codes."""
        for status in [500, 502, 503, 504]:
            entry = AccessLogEntry(
                method="GET", path="/", status_code=status, duration_ms=1.0
            )
            assert entry.is_error is True
    
    def test_is_error_property_non_error(self):
        """Test is_error returns False for non-error status codes."""
        for status in [100, 200, 201, 301, 302]:
            entry = AccessLogEntry(
                method="GET", path="/", status_code=status, duration_ms=1.0
            )
            assert entry.is_error is False
    
    def test_duration_ms_must_be_non_negative(self):
        """Test that duration_ms must be non-negative."""
        with pytest.raises(ValueError):
            AccessLogEntry(method="GET", path="/", status_code=200, duration_ms=-1.0)
    
    def test_with_error_detail(self):
        """Test entry with error detail."""
        entry = AccessLogEntry(
            method="POST",
            path="/email/send",
            status_code=500,
            duration_ms=100.0,
            error_detail="Internal server error",
        )
        
        assert entry.error_detail == "Internal server error"
        assert entry.is_error is True


# =============================================================================
# AccessLog Basic Operations Tests
# =============================================================================


class TestAccessLog:
    """Tests for AccessLog basic operations."""
    
    def test_instantiation_default_max_entries(self):
        """Test AccessLog with default max_entries."""
        log = AccessLog()
        
        assert log.max_entries == 10000
        assert log.count == 0
        assert log.is_full is False
    
    def test_instantiation_custom_max_entries(self):
        """Test AccessLog with custom max_entries."""
        log = AccessLog(max_entries=100)
        
        assert log.max_entries == 100
    
    def test_instantiation_invalid_max_entries(self):
        """Test that max_entries must be at least 1."""
        with pytest.raises(ValueError, match="max_entries must be at least 1"):
            AccessLog(max_entries=0)
        
        with pytest.raises(ValueError, match="max_entries must be at least 1"):
            AccessLog(max_entries=-5)
    
    def test_log_single_entry(self):
        """Test logging a single entry."""
        log = AccessLog()
        entry = AccessLogEntry(
            method="GET", path="/test", status_code=200, duration_ms=1.0
        )
        
        log.log(entry)
        
        assert log.count == 1
    
    def test_log_multiple_entries(self):
        """Test logging multiple entries."""
        log = AccessLog()
        
        for i in range(5):
            entry = AccessLogEntry(
                method="GET", path=f"/test/{i}", status_code=200, duration_ms=1.0
            )
            log.log(entry)
        
        assert log.count == 5
    
    def test_log_respects_max_entries(self):
        """Test that log respects max_entries limit."""
        log = AccessLog(max_entries=5)
        
        # Log 10 entries
        for i in range(10):
            entry = AccessLogEntry(
                log_id=f"entry-{i}",
                method="GET",
                path=f"/test/{i}",
                status_code=200,
                duration_ms=1.0,
            )
            log.log(entry)
        
        assert log.count == 5
        assert log.is_full is True
        
        # Verify oldest entries were removed (entries 0-4 should be gone)
        assert log.get_by_id("entry-0") is None
        assert log.get_by_id("entry-4") is None
        # Newest entries should remain
        assert log.get_by_id("entry-5") is not None
        assert log.get_by_id("entry-9") is not None
    
    def test_get_by_id_found(self):
        """Test get_by_id when entry exists."""
        log = AccessLog()
        entry = AccessLogEntry(
            log_id="test-123",
            method="GET",
            path="/test",
            status_code=200,
            duration_ms=1.0,
        )
        log.log(entry)
        
        found = log.get_by_id("test-123")
        
        assert found is not None
        assert found.log_id == "test-123"
    
    def test_get_by_id_not_found(self):
        """Test get_by_id when entry doesn't exist."""
        log = AccessLog()
        entry = AccessLogEntry(
            log_id="test-123",
            method="GET",
            path="/test",
            status_code=200,
            duration_ms=1.0,
        )
        log.log(entry)
        
        found = log.get_by_id("nonexistent")
        
        assert found is None
    
    def test_clear_empty_log(self):
        """Test clearing an empty log."""
        log = AccessLog()
        
        cleared = log.clear()
        
        assert cleared == 0
        assert log.count == 0
    
    def test_clear_populated_log(self):
        """Test clearing a populated log."""
        log = AccessLog()
        for i in range(5):
            log.log(AccessLogEntry(
                method="GET", path="/test", status_code=200, duration_ms=1.0
            ))
        
        cleared = log.clear()
        
        assert cleared == 5
        assert log.count == 0
    
    def test_is_full_property(self):
        """Test is_full property."""
        log = AccessLog(max_entries=3)
        
        assert log.is_full is False
        
        log.log(AccessLogEntry(method="GET", path="/1", status_code=200, duration_ms=1.0))
        assert log.is_full is False
        
        log.log(AccessLogEntry(method="GET", path="/2", status_code=200, duration_ms=1.0))
        assert log.is_full is False
        
        log.log(AccessLogEntry(method="GET", path="/3", status_code=200, duration_ms=1.0))
        assert log.is_full is True


# =============================================================================
# AccessLog Query Tests
# =============================================================================


class TestAccessLogQuery:
    """Tests for AccessLog query functionality."""
    
    @pytest.fixture
    def populated_log(self):
        """Create a log with various entries for testing queries."""
        log = AccessLog()
        now = datetime.now(timezone.utc)
        
        # Add entries with different characteristics
        entries = [
            # Success entries
            AccessLogEntry(
                log_id="entry-1",
                timestamp=now - timedelta(hours=2),
                method="GET",
                path="/email/state",
                key_id="ues_key1",
                key_name="Bot 1",
                status_code=200,
                duration_ms=10.0,
            ),
            AccessLogEntry(
                log_id="entry-2",
                timestamp=now - timedelta(hours=1),
                method="POST",
                path="/email/send",
                key_id="ues_key1",
                key_name="Bot 1",
                status_code=201,
                duration_ms=50.0,
            ),
            # Different key
            AccessLogEntry(
                log_id="entry-3",
                timestamp=now - timedelta(minutes=30),
                method="GET",
                path="/sms/state",
                key_id="ues_key2",
                key_name="Bot 2",
                status_code=200,
                duration_ms=15.0,
            ),
            # Error entries
            AccessLogEntry(
                log_id="entry-4",
                timestamp=now - timedelta(minutes=15),
                method="POST",
                path="/email/send",
                key_id="ues_key1",
                key_name="Bot 1",
                status_code=400,
                duration_ms=5.0,
                error_detail="Invalid request",
            ),
            AccessLogEntry(
                log_id="entry-5",
                timestamp=now - timedelta(minutes=5),
                method="GET",
                path="/calendar/state",
                key_id="ues_key1",
                key_name="Bot 1",
                status_code=500,
                duration_ms=100.0,
                error_detail="Server error",
            ),
        ]
        
        for entry in entries:
            log.log(entry)
        
        return log, now
    
    def test_query_no_filters(self, populated_log):
        """Test query with no filters returns all entries (newest first)."""
        log, _ = populated_log
        
        results = log.query()
        
        assert len(results) == 5
        # Should be newest first
        assert results[0].log_id == "entry-5"
        assert results[-1].log_id == "entry-1"
    
    def test_query_by_key_id(self, populated_log):
        """Test query filtering by key_id."""
        log, _ = populated_log
        
        results = log.query(key_id="ues_key1")
        
        assert len(results) == 4
        assert all(e.key_id == "ues_key1" for e in results)
    
    def test_query_by_key_name(self, populated_log):
        """Test query filtering by key_name."""
        log, _ = populated_log
        
        results = log.query(key_name="Bot 2")
        
        assert len(results) == 1
        assert results[0].key_name == "Bot 2"
    
    def test_query_by_path_prefix(self, populated_log):
        """Test query filtering by path prefix."""
        log, _ = populated_log
        
        results = log.query(path_prefix="/email")
        
        assert len(results) == 3
        assert all(e.path.startswith("/email") for e in results)
    
    def test_query_by_method(self, populated_log):
        """Test query filtering by HTTP method."""
        log, _ = populated_log
        
        results = log.query(method="GET")
        
        assert len(results) == 3
        assert all(e.method == "GET" for e in results)
    
    def test_query_by_method_case_insensitive(self, populated_log):
        """Test that method filter is case-insensitive."""
        log, _ = populated_log
        
        results_lower = log.query(method="get")
        results_upper = log.query(method="GET")
        results_mixed = log.query(method="Get")
        
        assert len(results_lower) == len(results_upper) == len(results_mixed) == 3
    
    def test_query_by_exact_status_code(self, populated_log):
        """Test query filtering by exact status code."""
        log, _ = populated_log
        
        results = log.query(status_code=200)
        
        assert len(results) == 2
        assert all(e.status_code == 200 for e in results)
    
    def test_query_by_status_code_range(self, populated_log):
        """Test query filtering by status code range."""
        log, _ = populated_log
        
        # Get all success responses (200-299)
        results = log.query(min_status_code=200, max_status_code=299)
        
        assert len(results) == 3
        assert all(200 <= e.status_code <= 299 for e in results)
    
    def test_query_by_min_status_code(self, populated_log):
        """Test query filtering by minimum status code."""
        log, _ = populated_log
        
        results = log.query(min_status_code=400)
        
        assert len(results) == 2
        assert all(e.status_code >= 400 for e in results)
    
    def test_query_by_max_status_code(self, populated_log):
        """Test query filtering by maximum status code."""
        log, _ = populated_log
        
        results = log.query(max_status_code=201)
        
        assert len(results) == 3
        assert all(e.status_code <= 201 for e in results)
    
    def test_query_since_timestamp(self, populated_log):
        """Test query filtering by since timestamp."""
        log, now = populated_log
        
        since = now - timedelta(minutes=20)
        results = log.query(since=since)
        
        assert len(results) == 2  # entry-4 (15 min ago) and entry-5 (5 min ago)
        assert all(e.timestamp >= since for e in results)
    
    def test_query_until_timestamp(self, populated_log):
        """Test query filtering by until timestamp."""
        log, now = populated_log
        
        until = now - timedelta(minutes=20)
        results = log.query(until=until)
        
        assert len(results) == 3  # entry-1, entry-2, entry-3
        assert all(e.timestamp < until for e in results)
    
    def test_query_timestamp_range(self, populated_log):
        """Test query filtering by timestamp range."""
        log, now = populated_log
        
        since = now - timedelta(minutes=45)
        until = now - timedelta(minutes=10)
        results = log.query(since=since, until=until)
        
        assert len(results) == 2  # entry-3 (30 min ago) and entry-4 (15 min ago)
    
    def test_query_errors_only(self, populated_log):
        """Test query filtering for errors only."""
        log, _ = populated_log
        
        results = log.query(errors_only=True)
        
        assert len(results) == 2
        assert all(e.is_error for e in results)
    
    def test_query_with_limit(self, populated_log):
        """Test query with limit."""
        log, _ = populated_log
        
        results = log.query(limit=2)
        
        assert len(results) == 2
        # Should be the 2 newest entries
        assert results[0].log_id == "entry-5"
        assert results[1].log_id == "entry-4"
    
    def test_query_with_offset(self, populated_log):
        """Test query with offset."""
        log, _ = populated_log
        
        results = log.query(offset=2)
        
        assert len(results) == 3
        # Should skip 2 newest, get entries 3, 2, 1
        assert results[0].log_id == "entry-3"
        assert results[-1].log_id == "entry-1"
    
    def test_query_with_limit_and_offset(self, populated_log):
        """Test query with both limit and offset (pagination)."""
        log, _ = populated_log
        
        # Get page 2 with page size 2
        results = log.query(limit=2, offset=2)
        
        assert len(results) == 2
        assert results[0].log_id == "entry-3"
        assert results[1].log_id == "entry-2"
    
    def test_query_combined_filters(self, populated_log):
        """Test query with multiple filters combined."""
        log, _ = populated_log
        
        results = log.query(
            key_id="ues_key1",
            method="POST",
            path_prefix="/email",
        )
        
        assert len(results) == 2  # entry-2 (201) and entry-4 (400)
        assert all(e.key_id == "ues_key1" for e in results)
        assert all(e.method == "POST" for e in results)
        assert all(e.path.startswith("/email") for e in results)
    
    def test_query_invalid_limit(self):
        """Test that negative limit raises ValueError."""
        log = AccessLog()
        
        with pytest.raises(ValueError, match="limit must be non-negative"):
            log.query(limit=-1)
    
    def test_query_invalid_offset(self):
        """Test that negative offset raises ValueError."""
        log = AccessLog()
        
        with pytest.raises(ValueError, match="offset must be non-negative"):
            log.query(offset=-1)
    
    def test_query_empty_log(self):
        """Test query on empty log."""
        log = AccessLog()
        
        results = log.query()
        
        assert results == []


# =============================================================================
# AccessLog Statistics Tests
# =============================================================================


class TestAccessLogStatistics:
    """Tests for AccessLog statistics functionality."""
    
    def test_statistics_empty_log(self):
        """Test statistics on empty log."""
        log = AccessLog()
        
        stats = log.get_statistics()
        
        assert stats["total_entries"] == 0
        assert stats["success_count"] == 0
        assert stats["client_error_count"] == 0
        assert stats["server_error_count"] == 0
        assert stats["unique_keys"] == 0
        assert stats["earliest_timestamp"] is None
        assert stats["latest_timestamp"] is None
    
    def test_statistics_with_entries(self):
        """Test statistics with various entries."""
        log = AccessLog()
        now = datetime.now(timezone.utc)
        
        # Add entries with different status codes and keys
        log.log(AccessLogEntry(
            timestamp=now - timedelta(hours=1),
            method="GET",
            path="/test",
            key_id="key1",
            status_code=200,
            duration_ms=1.0,
        ))
        log.log(AccessLogEntry(
            timestamp=now - timedelta(minutes=30),
            method="GET",
            path="/test",
            key_id="key1",
            status_code=201,
            duration_ms=1.0,
        ))
        log.log(AccessLogEntry(
            timestamp=now - timedelta(minutes=15),
            method="GET",
            path="/test",
            key_id="key2",
            status_code=400,
            duration_ms=1.0,
        ))
        log.log(AccessLogEntry(
            timestamp=now,
            method="GET",
            path="/test",
            key_id=None,  # Unauthenticated
            status_code=500,
            duration_ms=1.0,
        ))
        
        stats = log.get_statistics()
        
        assert stats["total_entries"] == 4
        assert stats["success_count"] == 2  # 200, 201
        assert stats["client_error_count"] == 1  # 400
        assert stats["server_error_count"] == 1  # 500
        assert stats["unique_keys"] == 3  # key1, key2, None
    
    def test_statistics_timestamps(self):
        """Test that statistics include correct timestamp range."""
        log = AccessLog()
        
        earliest = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        latest = datetime(2024, 1, 1, 12, 0, 0, tzinfo=timezone.utc)
        
        log.log(AccessLogEntry(
            timestamp=earliest,
            method="GET",
            path="/test",
            status_code=200,
            duration_ms=1.0,
        ))
        log.log(AccessLogEntry(
            timestamp=datetime(2024, 1, 1, 11, 0, 0, tzinfo=timezone.utc),
            method="GET",
            path="/test",
            status_code=200,
            duration_ms=1.0,
        ))
        log.log(AccessLogEntry(
            timestamp=latest,
            method="GET",
            path="/test",
            status_code=200,
            duration_ms=1.0,
        ))
        
        stats = log.get_statistics()
        
        assert stats["earliest_timestamp"] == earliest
        assert stats["latest_timestamp"] == latest
    
    def test_statistics_3xx_not_counted_as_error(self):
        """Test that 3xx responses are not counted as errors."""
        log = AccessLog()
        
        log.log(AccessLogEntry(
            method="GET", path="/test", status_code=301, duration_ms=1.0
        ))
        log.log(AccessLogEntry(
            method="GET", path="/test", status_code=302, duration_ms=1.0
        ))
        
        stats = log.get_statistics()
        
        assert stats["total_entries"] == 2
        assert stats["success_count"] == 0
        assert stats["client_error_count"] == 0
        assert stats["server_error_count"] == 0
